site_name: Gen-AI Cyber Security IITK
site_description: Cybersecurity Labs and Technical Documentation
site_url: https://sitename.example

extra_css:
  - styles.css

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.action.edit

  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md

  - Labs:
      - Prerequisites & Tools:
          - Installation Process: prerequisites/index.md

      - Foundations & System Security:
          - Microsoft Threat Modeling Tool: foundations-and-system-security/microsoft-threat-model-software/index.md
          - OWASP Threat Dragon: foundations-and-system-security/owasp-threat-dragon/index.md
          - Zero Trust Architecture: foundations-and-system-security/zero-day-trust/index.md
          - Network Traffic Fundamentals: foundations-and-system-security/network-traffic-fundamentals/index.md
          - Firewall Fundamentals using GUFW: foundations-and-system-security/firewall-fundamentals/index.md
          - VPN Fundamentals using OpenVPN: foundations-and-system-security/vpn-fundamentals/index.md
          - Linux OS Hardening: foundations-and-system-security/linux-hardening/index.md
          - Windows OS Hardening: foundations-and-system-security/windows-hardening/index.md

      - Pentesting & Ethical Hacking:
          - Reconnaissance and OSINT Part 1: pentesting-and-ethical-hacking/osint-part-1/index.md
          - Reconnaissance and OSINT Part 2: pentesting-and-ethical-hacking/osint-part-2/index.md
          - Vulnerability Scanning - Nmap Advanced Scanning & Nessus: pentesting-and-ethical-hacking/vulnerability-scanning-nmap-advanced-scanning-nessus/index.md
          - Web App Security Part 1 - Auth & Session Attacks, SQLi: pentesting-and-ethical-hacking/webapp-sec-part-1/index.md
          - Web App Security Part 2 - XSS, IDOR, CSRF: pentesting-and-ethical-hacking/webapp-sec-part-2/index.md
          - Web App & API Security - SSRF, RCE: pentesting-and-ethical-hacking/webapp-api-part-1/index.md
          - Web App & API Security - API Security: pentesting-and-ethical-hacking/webapp-api-part-2/index.md
          - Exploitation Techniques 1 - Metasploit Framework (Exploits & Payload Delivery): pentesting-and-ethical-hacking/exploitation-techniques-1/index.md
          - Exploitation Techniques 2 - Shell Handling and Privilege Escalation: pentesting-and-ethical-hacking/exploitation-techniques-2/index.md
          #- Exploitation Techniques 3 - Post-Exploitation Basics:
          #- Wireless Security - WPA2 Cracking Execution, Rogue AP:

      - Advance Red Teaming & AI-Driven Attacks:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - SOC, DFIR & AIML for Defense:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - Cloud Security, DevSecOps & Quantum Security:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md
