site_name: Gen-AI Cyber Security IITK
site_description: Cybersecurity Labs and Technical Documentation
site_url: https://sitename.example

extra_css:
  - styles.css

theme:
  name: material
  custom_dir: overrides

  features:
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.tabs.link
    - content.action.edit

  palette:
    - scheme: default
      primary: blue grey
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode

    - scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true

  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - search

nav:
  - Home: index.md

  - Labs:
      - Foundations & System Security:
          - Microsoft Threat Modeling Tool: foundations-and-system-security/microsoft-threat-model-software/index.md
          - OWASP Threat Dragon: foundations-and-system-security/owasp-threat-dragon/index.md
          - Zero Trust Architecture: foundations-and-system-security/zero-day-trust/index.md
          - Network Traffic Fundamentals: foundations-and-system-security/network-traffic-fundamentals/index.md

      - Pentesting & Ethical Hacking:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - Advance Red Teaming & AI-Driven Attacks:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - SOC, DFIR & AIML for Defense:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - Cloud Security, DevSecOps & Quantum Security:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md

      - Capstone Project:
          - Coming Soon: pentesting-and-ethical-hacking\coming-soon\index.md
